apiVersion: v1
kind: ConfigMap
metadata:
  name: helm
  namespace: girus
  labels:
    app: girus-lab-template
data:
  lab.yaml: |
    name: helm
    title: "Meu lab de test"
    description: "Lab de helm."
    duration: 30m
    timerEnabled: true
    maxDuration: 45m
    image: "linuxtips/girus-localstack:0.1"
    privileged: true
    type: "test"
    entrypoint: "/entrypoint.sh"
    tasks:
      - name: "Desafio 1: Preparar o Ambiente"
        description: "Prepare o ambiente para o desafio configurando as ferramentas necessárias"
        steps:
          - "Instale o editor Vim:"
        tips:
          - type: "info"
            title: "Requisitos"
            content: "Você precisará do Vim e jq para completar este desafio."
        validation:
          - command: "which vim > /dev/null && echo 'success' || echo 'error'"
            expectedOutput: "success"
            errorMessage: "O Vim não foi instalado corretamente. Instale-o usando 'apt install -y vim'."